name: Deploy to GitHub Pages and Docker Hub

on:
  push:
    branches: [master, feature]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HTML Lint
        uses: html-validator/action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: '.'   # Патека до HTML датотеките, може да се смени ако треба

  build-docker:
    runs-on: ubuntu-latest
    needs: lint-html
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest .
          echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest" >> $GITHUB_ENV

  docker-push:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest

  deploy-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: lint-html
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
